@startuml
actor User

actor Dealer

package BlackJack{
  usecase "ゲームを開始する" as UC1
  usecase "カードを引く" as UC2
  usecase "点数を判定する" as UC3
  usecase "勝敗を判定する" as UC4
}
UC1 --> UC2
UC2 --> UC3
UC3 --> UC4
User--> UC1
User--> UC2
User--> UC3
User--> UC4

Dealer--> UC1
Dealer--> UC2
Dealer--> UC3
Dealer--> UC4
@enduml
